### ISSUE TITLE
[BUG] ouput will break with unicode

### ISSUE THREAD

**Issue by leemannd** [camptocamp/anthem#30]
DJ_tool is creating songs with in comments the name of the company. Anthem use this comment as a log.
If you have a company_name with characters like `é` it will fail.
We have to eighter fix it in anthem or dj_tool
https://github.com/camptocamp/anthem/blob/master/anthem/output.py#L28

https://hastebin.com/kajozicujo.swift

**Comment by simahawk** [comment]
it's in DJ
