### ISSUE TITLE
[Question] How to upgrade modules with anthem without restarting the server?

### ISSUE THREAD

**Issue by obayit** [camptocamp/anthem#55]
I have this method that is supposed to upgrade a list of modules:
```
@anthem.log
def upgrade_list(ctx):
    """ upgrade module """
    module_list = ['hr', 'purchase']
    mods = ctx.env['ir.module.module'].search([('name', 'in', module_list), ('state', '=', 'installed')])
    if mods:
        mods.button_immediate_upgrade()
```

Odoo version 12

The upgrade doesn't take effect until the server is restarted!
I tried to change the `name` of an `ir.ui.menu` and it changed in the database but didn't change in the browser!

How can I upgrade modules without restarting the server?

**Comment by oerp-odoo** [comment]
You should probably use `migration.yml` file instead, because updating modules after they are loaded, can corrupt you data and is tricky. Why you want to update it this way?

**Comment by obayit** [comment]
What do you mean by corrupt the data? btw, the code above is trimmed. I do check if the server needs a restart or not.
Here is the full code
```
@anthem.log
def auto_deploy(ctx):
    """ upgrade module """

    service_name, restart_required, module_list = pull_changes.run()
    if not module_list:
        print('nothing to upgrade')
        return
    if restart_required:
        print('#*Stopping Odoo Server')
        stop_odoo_proc = subprocess.Popen(['sudo', 'service', service_name, 'stop'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    try:
        mods = ctx.env['ir.module.module'].search([('name', 'in', module_list), ('state', '=', 'installed')])
        if mods:
            mods.button_immediate_upgrade()
        else:
            print('#notify, changed modules are not installed')
    except Exception:
        raise AnthemError(u'Cannot upgrade modules. See the logs')
    stop_odoo_proc = subprocess.Popen(['sudo', 'service', service_name, 'start'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
```

Yeah I will take a look at `marabunta`.

**Comment by guewen** [comment]
> I tried to change the `name` of an `ir.ui.menu` and it changed in the database but didn't change in the browser!

Hi,

When calling `button_immediate_upgrade`, it will call:

* `IrModuleModule_button_immediate_function()` which calls `Registry.new` with `update_module=True` https://github.com/odoo/odoo/blob/1a5f71bec0073197e2eacc7929d79599ccff250d/odoo/addons/base/models/ir_module.py#L573
* `Registry.new` set the flag `registry_invalidated` to True: https://github.com/odoo/odoo/blob/1a5f71bec0073197e2eacc7929d79599ccff250d/odoo/modules/registry.py#L102
* The next time `signal_changes()` is called on the registry, it will propagate the invalidation to the other workers: https://github.com/odoo/odoo/blob/1a5f71bec0073197e2eacc7929d79599ccff250d/odoo/modules/registry.py#L463

Maybe in the case of anthem, `signal_changes()` is not called automatically, as by default it is called only at the end of a request/cron. 

At this line: https://github.com/camptocamp/anthem/blob/8883cef5936466195641b485333d83264e19f3d6/anthem/cli.py#L129
We could get the registry for the current db and call `signal_changes` on it if `self.options.test_mode` is False and `exc_type` is None? Could you try it?
